### PR TITLE
add support for privately hosted git repositories

### PR DESCRIPTION
**Pull request by repomaa**
- This removes the exception about unsupported sites
- Any git repository hosted anywhere can be used
- Remove existing directory before clone when ran with --force

### CODE REVIEW

**Comment by repomaa** [comment]
I'm aware that there's no test for this... Not sure how it should be done without relying on someone's private git server.

**Comment by nake89** [comment]
A welcome feature :)

**Comment by nake89** [comment]
@repomaa 
I ran tests locally and everything seemed to work. I also updated the version and tested that it seems to work.
But these tests are worrying: https://github.com/tiged/tiged/pull/7/checks?check_run_id=2051135208
```
  2) degit
       bitbucket
         bitbucket:Rich_Harris/degit-test-repo:
     Error: Command failed: node /home/runner/work/tiged/tiged/dist/bin.js bitbucket:Rich_Harris/degit-test-repo .tmp/test-repo -v
! could not fetch remote https://bitbucket/Rich_Harris/degit-test-repo
> Command failed: git ls-remote https://bitbucket/Rich_Harris/degit-test-repo
fatal: unable to access 'https://bitbucket/Rich_Harris/degit-test-repo/': Could not resolve host: bitbucket
```
Could that be due to your change?
I also tried to run this locally
```
~/projects/tiged-fix >>> node /home/runner/work/tiged/tiged/dist/bin.js bitbucket:Rich_Harris/degit-test-repo .tmp/test-repo -v
~/projects/tiged-fix >>> node dist/bin.js bitbucket:Rich_Harris/degit-test-repo .tmp/test-repo -v
! could not fetch remote https://bitbucket/Rich_Harris/degit-test-repo
> Command failed: git ls-remote https://bitbucket/Rich_Harris/degit-test-repo
fatal: unable to access 'https://bitbucket/Rich_Harris/degit-test-repo/': Could not resolve host: bitbucket

> using cached commit hash e62cde59d847e4b20a4be6ef6438fd179e04a4fb
> /home/nake89/.degit/bitbucket/Rich_Harris/degit-test-repo/e62cde59d847e4b20a4be6ef6438fd179e04a4fb.tar.gz already exists locally
> extracting /home/nake89/.degit/bitbucket/Rich_Harris/degit-test-repo/e62cde59d847e4b20a4be6ef6438fd179e04a4fb.tar.gz to .tmp/test-repo
> cloned Rich_Harris/degit-test-repo#HEAD to .tmp/test-repo
```

**I think my tests didn't fail because degit was able to get it from the cache.**
Reverting for now.

**Comment by repomaa** [comment]
ah i see. I didn't realize there was a cache. Is it possible to disable the cache for the tests (except for those that test the cache :))

**Comment by repomaa** [comment]
@nake89 say hi to my home town vantaa for me :)

**Pull request merged**
