### PR TITLE
fix: full async + cjs (no build need)

### PR DESCRIPTION
**Pull request by devthejo**

### CODE REVIEW

**Comment by nake89** [comment]
I've been testing this and it looks good to me.
That said. I noticed that this breaks compatibility with node v8. Node 10 still works for this. 
But that is not a supported version of node anyway. Even node 12 is ending it's maintenance support. So in my opinion this is definitely good enough.

I just need to update the read me to mirror this. Currently it says that version 10 is supported.

I will merge this pull request.

**Comment by nake89** [comment]
I will publish new version soon.

**Comment by nake89** [comment]
New version published.

**Comment by devthejo** [comment]
Thank you very much for your reactivity and for the great job on this tool !
Best regards :-)

**Pull request merged**
