### PR TITLE
Update `CHANGELOG.md` with changes in #89

### PR DESCRIPTION
**Pull request by aryaemami59**
## **This PR**:

- [X] Updates `CHANGELOG.md` with changes in #89.

### CODE REVIEW

**Comment by aryaemami59** [comment]
@nake89 Is this good or do you want me to include more details?

**Comment by nake89** [comment]
I'm trying to think what would be good info to tell the people who read the CHANGELOG.md.

Maybe you can add a nested list. You can use your own discretion.

Suggestions. Maybe these are important?
- Replaces mocha with Vitest as it has better ESM and TypeScript support.
- Replaces rollup and other rollup related dev dependencies with tsup.

Not sure if this is important:
- Uses tsup to output both CJS and ESM entry points.

Because I only use tiged as CLI tool. But people who import or require or whatever might be interested? Dunno :D

**Comment by aryaemami59** [comment]
Sure I can add more details.

**Comment by aryaemami59** [comment]
@nake89 I would love that, it seems like the link is not valid though.

**Comment by nake89** [comment]
Thanks for letting me know. Hopefully this works: https://discord.gg/bNHqU797ee
I'll update it to the read me soon.

**Pull request merged**
