### PR TITLE
Migrate codebase to TypeScript

### LINKED ISSUE #85: add typescript support
This package doesn't has typescript support out of the box.
Is it having the same type signature as degit?
If so, we can copy @types/degit into @types/tiged.

### PR DESCRIPTION
**Pull request by aryaemami59**
**This PR**:

  - [X] Converts the entire codebase to use TypeScript by default.
  - [X] Replaces mocha with Vitest as it has better ESM and TypeScript support.
  - [X] Replaces rollup and other rollup related dev dependencies with tsup.
  - [X] Uses tsup to output both CJS and ESM entry points.
  - [X] Bumps ESLint and Prettier.
  - [X] Adds `@typescript-eslint` packages to help with linting TypeScript files.
  - [X] Migrates ESLint to use the new flat config.
  - [X] Runs Prettier on all files.
  - [x] Adds JSDocs to everything to make sure the entirety of both the runtime code and types are well documented. 
  - [X] Resolves #85

### CODE REVIEW

**Comment by nake89** [comment]
Is this ready?

**Comment by aryaemami59** [comment]
@nake89 Thank you!

**Comment by nake89** [comment]
There is a failing test:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 3 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
AssertionError: expected 'tiged is awesome' to be '# tiged-test\nFor testing' // Object.is equality

- Expected
+ Received

- # tiged-test
- For testing
+ tiged is awesome

 ❯ test/index.test.ts:39:53
     37|    const filePath = path.join(`${dir}/${file}`);
     38|    if (!(await fs.lstat(filePath)).isDirectory()) {
     39|     expect(path.join(normalizedPaths[file]).trim()).toBe(
       |                                                     ^
     40|      (await read(filePath)).trim()
     41|     );

This error originated in "test/index.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "is able to clone correctly using git mode with old hash". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
AssertionError: expected 'Hello, buddy!' to be 'Hello, champ!' // Object.is equality

- Expected
+ Received

- Hello, champ!
+ Hello, buddy!

 ❯ test/index.test.ts:39:53
     37|    const filePath = path.join(`${dir}/${file}`);
     38|    if (!(await fs.lstat(filePath)).isDirectory()) {
     39|     expect(path.join(normalizedPaths[file]).trim()).toBe(
       |                                                     ^
     40|      (await read(filePath)).trim()
     41|     );

This error originated in "test/index.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "is able to clone correctly using git mode with old hash". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
AssertionError: expected 'Hello, buddy!' to be 'Hello, champ!' // Object.is equality

- Expected
+ Received

- Hello, champ!
+ Hello, buddy!

 ❯ test/index.test.ts:39:53
     37|    const filePath = path.join(`${dir}/${file}`);
     38|    if (!(await fs.lstat(filePath)).isDirectory()) {
     39|     expect(path.join(normalizedPaths[file]).trim()).toBe(
       |                                                     ^
     40|      (await read(filePath)).trim()
     41|     );

This error originated in "test/index.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "is able to clone subdir correctly using git mode with old hash". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

**Comment by aryaemami59** [comment]
@nake89 can you clear the global cache and try again? I noticed the cache wasn't being cleared in between tests and it was creating side effects and causing some issues.

**Comment by nake89** [comment]
I deleted my cache and tried again. But still got the same error. I'm on a mac.

On line 246 of your test file it is using hash 525e8fef2c6b5e261511adc55f410d83ca5d8256.

When we look at that file:
https://github.com/tiged/tiged-test/blob/525e8fef2c6b5e261511adc55f410d83ca5d8256/subdir/file

It says:
`Hello, champ!`

But the code is expecting:
`Hello, buddy!`

https://github.com/tiged/tiged-test/blob/525e8fef2c6b5e261511adc55f410d83ca5d8256/README.md
Also returns something older and not `tiged is awesome`

Same goes for line 256 on the test file, which uses hash b09755bc4cca3d3b398fbe5e411daeae79869581.
https://github.com/tiged/tiged-test/blob/b09755bc4cca3d3b398fbe5e411daeae79869581/subdir/file

**Comment by aryaemami59** [comment]
@nake89 Does the code behave differently on Windows?

**Comment by nake89** [comment]
Sorry for my unannounced hiatus. I'm back. Will create an RC v3.0 version for this PR. I will also be looking at tiged caching functionality in the RC. When ready I will publish v3.0 with this project forked to TS and with some "breaking" API changes related to the currently weirdly behaving caching. Stay tuned.

**Comment by aryaemami59** [comment]
@nake89 Awesome, thank you! Just one question. Is it ok if the `degit` function (which is the default export of this library), become a named export? it would be much easier to have interoperability between ESM and CJS that way, but it would be a breaking change.

Also with regards to the caching behavior, I did make some adjustments to it in this PR, it might be worth looking at some of those changes :)

And I would like to help with RC v3.0 if you need me to :)

**Comment by nake89** [comment]
Ok. I finally published it. Version: tiged@3.0.0-rc.0
Currently a release candidate. You can test it by installing it: npm i -g tiged@3.0.0-rc.0

I still don't quite understand how releasing release candidates work and what prevents this version as being installed as a default. Probably the hyphen. Dunno.

Regardless. According to the tests everything runs beautifully.

Super super huge thanks to aryaemami59 for his amazingly huge work on this. I will setup a credits section on the README to credit you properly. I might consider adding you as a maintainer if you are interested. I am slightly concerned how that works though. So I want to setup some reasonable permissions etc. I don't want anybody hijacking this project.

There is nothing huge stopping me from posting an actual major version. But I do want to checkout some improvement suggestions and some PRs. So that this major version has some more improvements.

Thanks again.

**Comment by aryaemami59** [comment]
@nake89 Thank you for merging this PR. I would love to become a collaborator on this project, though I understand if you prefer not to do that.

One small suggestion I have is that, since we are going to have a new major version and can include breaking changes, it might be good to remove the `default` export and make `tiged` a named export. This would make ESM/CJS interoperability much easier.

**Comment by aryaemami59** [comment]
BTW it looks like the `latest` tag is pointed to the new `rc` version. To fix it you might have to do something like:

```bash
npm publish --tag rc
```

**Comment by nake89** [comment]
Thanks for letting me know.
Should be fixed now.
https://www.npmjs.com/package/tiged?activeTab=versions

**Comment by nake89** [comment]
@aryaemami59 Hey is there a chance that you could update your changes to the CHANGELOG.md.

**Comment by aryaemami59** [comment]
@nake89 You mean add the changes I made in this PR to the `CHANGELOG.md`?

**Comment by nake89** [comment]
Yes, please. You create a version 3.0.0. in the CHANGELOG.md file.

**Comment by aryaemami59** [comment]
@nake89 Yes sir!

**Pull request merged**
