### PR TITLE
Remove `fs-extra`

### PR DESCRIPTION
**Pull request by aryaemami59**
## **This PR**:

- [X] Adds `pathExists` utility function.
- [X] Adds `isDirectory` utility function.
- [X] Replaces usages of `fs-extra` with `node:fs/promises`.
- [X] Removes `fs-extra`.

### CODE REVIEW

**Comment by nake89** [comment]
Does this change the required version of node?

**Comment by aryaemami59** [comment]
> Does this change the required version of node?

Probably, I'll look into it and let you know.

**Comment by nake89** [comment]
We used to be able to run tiged with a fairly low node version. I'm fine with raising it. But we need to mention it on the readme. Maybe to add a requirements section. Looking at the Node LTS versions it seems that node 18 is not EOL yet so if it supports at least that I'm happy. Makes me feel old.

**Comment by aryaemami59** [comment]
@nake89 gotcha lemme do some testing and see.

**Comment by aryaemami59** [comment]
@nake89 Looks like we can support v16 onwards though I would feel a lot more comfortable if we can document it as v18 onwards considering most of the dependencies also support v18.

**Comment by nake89** [comment]
Sounds good. Can I merge this?

**Comment by aryaemami59** [comment]
@nake89 Yes please!

**Pull request merged**
